# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a53g/setup-makefiles.sh

#Binaries
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/a53g/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/samsung/a53g/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/samsung/a53g/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/a53g/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/samsung/a53g/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/a53g/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/samsung/a53g/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/a53g/proprietary/bin/ssr_diag:system/bin/ssr_diag \
    vendor/samsung/a53g/proprietary/bin/ssr_setup:system/bin/ssr_setup \
    vendor/samsung/a53g/proprietary/bin/subsystem_ramdump:system/bin/subsystem_ramdump
    
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    vendor/samsung/a53g/proprietary/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
    vendor/samsung/a53g/proprietary/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
    vendor/samsung/a53g/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    vendor/samsung/a53g/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    vendor/samsung/a53g/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    vendor/samsung/a53g/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libhwdaphal.so:system/vendor/lib/libhwdaphal.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/samsung/a53g/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/a53g/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    vendor/samsung/a53g/proprietary/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libmdsprpc.so:system/vendor/lib/libmdsprpc.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqti-at.so:system/vendor/lib/libqti-at.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/samsung/a53g/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/samsung/a53g/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libSampleAuthJNI.so:system/vendor/lib/libSampleAuthJNI.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libscve_mv.so:system/vendor/lib/libscve_mv.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsd_sdk_display.so:system/vendor/lib/libsd_sdk_display.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsmwrapper.so:system/vendor/lib/libsmwrapper.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsregex.so:system/vendor/lib/libsregex.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libvcel.so:system/vendor/lib/libvcel.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libwms.so:system/vendor/lib/libwms.so

#Audio
PRODUCT_COPY_FILES += \
     vendor/samsung/a53g/proprietary/lib/hw/audio.primary.msm8916.so:system/lib/hw/audio.primary.msm8916.so
#    vendor/samsung/a53g/proprietary/lib/libaudioroute.so:system/lib/libaudioroute.so \
#    vendor/samsung/a53g/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
#    vendor/samsung/a53g/proprietary/lib/libmysound.so:system/lib/libmysound.so \
#    vendor/samsung/a53g/proprietary/lib/libtfa9895.so:system/lib/libtfa9895.so \
#    vendor/samsung/a53g/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

#GPS
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/samsung/a53g/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/samsung/a53g/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/a53g/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/samsung/a53g/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/a53g/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/samsung/a53g/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/samsung/a53g/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/a53g/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so

#RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/a53g/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/a53g/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/a53g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/a53g/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/a53g/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/a53g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/a53g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so
    
#Ims
#PRODUCT_COPY_FILES += \
#    vendor/samsung/a53g/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
#    vendor/samsung/a53g/proprietary/bin/imscmservice:system/bin/imscmservice \
#    vendor/samsung/a53g/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
#    vendor/samsung/a53g/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-ims-rcscmjni.so:system/vendor/lib/lib-ims-rcscmjni.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsrcscm.so:system/vendor/lib/lib-imsrcscm.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsrcscmclient.so:system/vendor/lib/lib-imsrcscmclient.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsrcscmservice.so:system/vendor/lib/lib-imsrcscmservice.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
#    vendor/samsung/a53g/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so
    
#Qmi
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so

#Widevine
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
    vendor/samsung/a53g/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/a53g/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    vendor/samsung/a53g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

#Time
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/samsung/a53g/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so
        
#Bluetooth
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/a53g/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/samsung/a53g/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init
    
#keystore
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/vendor/lib/libSecureSampleAuthClient.so:system/vendor/lib/libSecureSampleAuthClient.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libSecureSampleAuthJNI.so:system/vendor/lib/libSecureSampleAuthJNI.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsecureuisvc_jni.so:system/vendor/lib/libsecureuisvc_jni.so

#Graphics
PRODUCT_COPY_FILES += \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/a53g/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/samsung/a53g/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/samsung/a53g/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so
    
